version: "3.8"

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqldata:/var/lib/mysql
    command: mysqld --sql_mode=""
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # Bun
  bun:
    build: ./.docker/bun
    volumes:
      - ./src/:/app
      - bun_node_modules:/app/node_modules
    ports:
      - 3000:3000

  # Postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

# Volumes
volumes:
  mysqldata:
  postgres:
    driver: local
  bun_node_modules:
